## everytime something is pushed to git, 
##generate feed
name: Generate Podcast Feed
on: [push]
## execute some jobs - specify what we want to do
jobs: 
  build:
    runs-on: Windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: kcurious/podcast-generator@main
      
